name: Healingwithpachamama
favicon: null
layout_spectrum: 0.5682968
typography_spectrum: 0.6804385
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#c4c3be'
    - '#0c0000'
    - '#fefefe'
    - '#f78500'
    - '#325400'
  brandStrength: 0.5
  lightness: 0.875
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
