name: Healingwithpachamama
favicon: null
layout_spectrum: 0.21854
typography_spectrum: 0.6804385
title: Regenerative Detoxification and Living Foods Workshops
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#234785'
    - '#4882c2'
    - '#fffffd'
    - '#afac9d'
    - '#121011'
  brandStrength: 0.5
  lightness: 0.875
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
