layout_spectrum: 0.5682968
color:
  saturation: 0.6222597
  lightness: 0.653457
  brandStrength: 0.4662732
  brandColors:
    - '#FDFDFD'
    - '#020202'
    - '#898D7F'
    - '#652309'
    - '#2B445E'
  rhythmicContrast: 0.435919
typography_spectrum: 0.6804385
name: Healingwithpachamama
